# Import the Libraries

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from scipy.signal import butter, lfilter
import pandas as pd
import numpy as np
import scipy.signal
# from numpy.core.multiarray import ndarray
# from scipy import signal
# import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# import seaborn as sn
import io
import matplotlib
import  matplotlib.pyplot as plt
from scipy import signal
import numpy as np
import scipy.signal
from scipy.signal import chirp, find_peaks, peak_widths, peak_prominences
from numpy import mean, median, std, percentile, fft, abs, argmax
from scipy.stats import norm, kurtosis, skew
import numpy as np
import scipy.signal
from scipy.signal import chirp, find_peaks, peak_widths, peak_prominences
from statsmodels.tsa import stattools
import math
from sklearn import linear_model, neighbors
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from scipy.stats import entropy
from scipy.fft import fft, ifft

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
f = open('/content/Normalizedfeatures.csv')
attributes=f.readline()
X = []
y = []
for line in f:
    line = line.rstrip().split(',')
    l = [float(i) for i in line]
    X.append(l[:-1])
    y.append(l[-1])
    
X = np.asarray(X)
y = np.asarray(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Feature Selection using P value

In [ ]:
X.shape

(2568, 174)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)


# print(X_train)
from sklearn.feature_selection import chi2
chi,p_value=chi2(X,y)
import pandas as pd
p_values=pd.Series(p_value)
# p_values.index=X_train
print("p_value",p_values)
# print("chi_square",chi)
print(p_value)

p_value 0      1.023277e-50
1      9.963228e-01
2      9.701008e-96
3      4.717678e-67
4      8.217080e-25
           ...     
169    6.105339e-05
170    9.770459e-02
171    1.176904e-03
172    7.584845e-06
173    1.471996e-04
Length: 174, dtype: float64
[1.02327692e-50 9.96322767e-01 9.70100831e-96 4.71767822e-67
 8.21707992e-25 1.43406372e-15 3.68725863e-03 1.07848841e-64
 7.39380857e-09 3.81693955e-01 3.08202735e-72 2.16878447e-77
 9.61734278e-06 9.72274363e-37 1.74500534e-34 3.69315742e-54
 8.74581411e-03 5.84218045e-03 3.19469358e-06 6.11968878e-03
 9.32304252e-01 4.21537891e-55 8.70683995e-01 9.37373254e-01
 2.54670652e-74 6.30797005e-91 5.32244429e-96 8.71127050e-01
 8.78892734e-01 5.18149447e-05 8.67335229e-01 9.36659163e-01
 7.48880044e-41 2.44827783e-75 4.17424011e-82 8.67521061e-01
 9.43716542e-01 6.96858580e-47 8.70681710e-01 9.35976341e-01
 9.46350274e-74 4.20778476e-91 4.07002372e-96 8.71096229e-01
 9.15974918e-01 5.89900006e-52 8.70128153e-01 9.36562277e-01
 3.50071410e

In [ ]:
s=[]
s=np.argsort(p_values)

In [ ]:
f=[]
f=s[:90,]


In [ ]:
X1=X[:,f]
print(y)

[1. 1. 1. ... 3. 3. 3.]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.25, random_state=42)

# Train classifiers using K-fold cross validation

In [ ]:
rf_scores = []
svml_score=[]
svmr_score=[]
dt=[]
k=[]

best_svr= RandomForestClassifier(criterion='entropy', max_depth=6, random_state=0)
clf12 = SVC(C=100, kernel='linear')
clf1 = SVC(C=100, kernel='rbf')
d=DecisionTreeClassifier(criterion='entropy',max_depth=3, max_leaf_nodes=10, random_state=0)
knn = neighbors.KNeighborsClassifier(n_neighbors=3)

from sklearn.model_selection import KFold
cv = KFold(n_splits=7)
for train_index, test_index in cv.split(X1):


    X_train, X_test, y_train, y_test = X1[train_index], X1[test_index], y[train_index], y[test_index]

    best_svr.fit(X_train, y_train)
    clf12.fit(X_train, y_train)
    clf1.fit(X_train, y_train)
    d.fit(X_train, y_train)
    knn.fit(X_train,y_train)

    rf_scores.append(best_svr.score(X_test, y_test))
    svml_score.append(clf12.score(X_test, y_test))
    svmr_score.append(clf1.score(X_test, y_test))
    dt.append(d.score(X_test, y_test))
    k.append(knn.score(X_test, y_test))
#
print("random_forest", rf_scores)
print(np.mean(rf_scores))
print("svm", svml_score)
print(np.mean(svml_score))
print("svmr", svmr_score)
print(np.mean(svmr_score))
print("dt",dt)
print(np.mean(dt))
print("knn",k)
print(np.mean(k))

random_forest [0.7166212534059946, 0.7329700272479565, 0.5803814713896458, 0.7329700272479565, 0.6239782016348774, 0.7384196185286104, 0.7513661202185792]
0.696672388524803
svm [0.7166212534059946, 0.8528610354223434, 0.7029972752043597, 0.8365122615803815, 0.7983651226158038, 0.9182561307901907, 0.8907103825136612]
0.8166176373618192
svmr [0.7166212534059946, 0.8337874659400545, 0.6975476839237057, 0.8446866485013624, 0.8283378746594006, 0.9264305177111717, 0.9153005464480874]
0.8232445700842538
dt [0.7138964577656676, 0.5885558583106267, 0.4332425068119891, 0.6566757493188011, 0.5013623978201635, 0.5858310626702997, 0.5737704918032787]
0.5790477892144038
knn [0.7138964577656676, 0.8555858310626703, 0.7275204359673024, 0.8092643051771117, 0.7929155313351499, 0.9073569482288828, 0.9207650273224044]
0.8181863624084557


# Individual Train and Test Accuracy

In [ ]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.25, random_state=42)
clf = RandomForestClassifier(criterion='entropy', max_depth=4, random_state=0)
clf.fit(X_train,y_train)
Test_rf = clf.predict(X_test) #Predict the test result & returns 1-D array
Test_accuracy=accuracy_score(y_true = y_test, y_pred = Test_rf)
Train_rf= clf.predict(X_train)
Train_accuracy=accuracy_score(y_true =y_train , y_pred = Train_rf)
print("Train Accuracy of RF  {}".format(Train_accuracy))
print("Test Accuracy of RF   {}".format(Test_accuracy))
cm = confusion_matrix(y_test, Test_rf)
print ("Confusion matrix:",cm)
y_pred = clf.predict(X_test)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

Train Accuracy of RF  0.8613707165109035
Test Accuracy of RF   0.8598130841121495
Confusion matrix: [[ 93   0  11]
 [  0 163  66]
 [  0  13 296]]
0.8723786329229991
0.9065673490941588
0.8546499882776221


In [ ]:
cli = [1,0.5,0.1,0.01,0.003,0.0003]
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.25, random_state=42)

trainacc = np.array([])
testacc = np.array([])
for j in cli:         #iterating through different penalty values
    LRmod = linear_model.LogisticRegression(penalty='l2', C=j)
    LRmod.fit(X_train,y_train)
    pred = LRmod.predict(X_test)
    pred1 = LRmod.predict(X_train)
    testac = accuracy_score(y_true = y_test, y_pred = pred)
    trainac = accuracy_score(y_true = y_train, y_pred = pred1)
    trainacc = np.append(trainacc,trainac)
    testacc = np.append(testacc,testac)
    print("Training Accuracy for penalty {}: {}".format(j,trainac))
    print("Testing Accuracy for penalty {}: {}".format(j,testac))
Accuracy_KNN = np.array([])
Accuracy_knn_train=np.array([])
rangeli = list(range(3,10))
for i in rangeli:
    knn = neighbors.KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    predicted_knn = knn.predict(X_test)
    predict_train=knn.predict(X_train)
    Accuracy = accuracy_score(y_true = y_test, y_pred = predicted_knn)
    Train_KnnAccuracy=accuracy_score(y_train,predict_train)
    print('==========',i ,  Accuracy,"Train_Acuracy : ",Train_KnnAccuracy)
    Accuracy_KNN = np.append(Accuracy_KNN, Accuracy)
    Accuracy_knn_train=np.append(Accuracy_knn_train,Train_KnnAccuracy)
print("Test_Optimal K value is {} Train_Optimal k value is {}".format(rangeli[np.argmax(Accuracy_KNN)],rangeli[np.argmax(Accuracy_knn_train)]))
print(f"Train Accuracy of optimum k value is : {np.max(Accuracy_knn_train)}")
print("Test Accuracy of Optimum K value is {}".format(np.max(Accuracy_KNN)))
Test1 = knn.predict(X_test)
cm1 = confusion_matrix(y_test, Test1)
print ("Confusion matrix:",cm1)
y_pred = knn.predict(X_test)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


Training Accuracy for penalty 1: 0.8660436137071651
Testing Accuracy for penalty 1: 0.8722741433021807


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


Training Accuracy for penalty 0.5: 0.8572170301142263
Testing Accuracy for penalty 0.5: 0.8629283489096573


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


Training Accuracy for penalty 0.1: 0.8037383177570093
Testing Accuracy for penalty 0.1: 0.8006230529595015
Training Accuracy for penalty 0.01: 0.7476635514018691
Testing Accuracy for penalty 0.01: 0.7445482866043613
Training Accuracy for penalty 0.003: 0.6593977154724818
Testing Accuracy for penalty 0.003: 0.6557632398753894
Training Accuracy for penalty 0.0003: 0.5960539979231568
Testing Accuracy for penalty 0.0003: 0.5872274143302181
========== 3 0.897196261682243 Train_Acuracy :  0.9470404984423676
========== 4 0.897196261682243 Train_Acuracy :  0.9304257528556594
========== 5 0.9065420560747663 Train_Acuracy :  0.9241952232606438
========== 6 0.897196261682243 Train_Acuracy :  0.9174454828660437
========== 7 0.8862928348909658 Train_Acuracy :  0.9127725856697819
========== 8 0.8862928348909658 Train_Acuracy :  0.9075804776739356
========== 9 0.883177570093458 Train_Acuracy :  0.9044652128764278
Test_Optimal K value is 5 Train_Optimal k value is 3
Train Accuracy of optimum k value i

In [ ]:
clf12 = SVC(C= 10, kernel='linear') #Loading the Data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)
print(f"X_test size {X_test.shape} and X_train size:{X_train.shape}")
clf12.fit(X_train,y_train) #Train The Data
Test_predsvm = clf12.predict(X_test) #Predict the test result & returns 1-D array
Test_accuracy=accuracy_score(y_true = y_test, y_pred = Test_predsvm)
Train_predsvm= clf12.predict(X_train)
Train_accuracy=accuracy_score(y_true =y_train , y_pred = Train_predsvm)
print("Train Accuracy of SVM  {}".format(Train_accuracy))
print("Test Accuracy of SVM   {}".format(Test_accuracy))
print(Train_predsvm)
# plt.bar(np.array(range(0,100)),Test_predsvm[0:100])
# plt.show()
cm = confusion_matrix(y_test, Test_predsvm)
print ("Confusion matrix:",cm)
y_pred = clf12.predict(X_test)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

X_test size (514, 174) and X_train size:(2054, 174)
Train Accuracy of SVM  0.9527750730282376
Test Accuracy of SVM   0.9591439688715954
[2. 3. 3. ... 3. 1. 2.]
Confusion matrix: [[ 68   0   0]
 [  0 170  16]
 [  0   5 255]]
0.9674267440829251
0.9707959936742224
0.9649159084642956


In [ ]:

clf1 = SVC(C=100, kernel='rbf') #Loading the Data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)
print(f"X_test size {X_test.shape} and X_train size:{X_train.shape}")
clf1.fit(X_train,y_train) #Train The Data
Test_predsvm = clf1.predict(X_test) #Predict the test result & returns 1-D array
Test_accuracy=accuracy_score(y_true = y_test, y_pred = Test_predsvm)
Train_predsvm= clf1.predict(X_train)
Train_accuracy=accuracy_score(y_true =y_train , y_pred = Train_predsvm)
print("Train Accuracy of SVM  {}".format(Train_accuracy))
print("Test Accuracy of SVM   {}".format(Test_accuracy))
print(Train_predsvm)
# plt.bar(np.array(range(0,100)),Test_predsvm[0:100])
# plt.show()
cm = confusion_matrix(y_test, Test_predsvm)
print ("Confusion matrix:",cm)
y_pred = clf1.predict(X_test)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

X_test size (514, 174) and X_train size:(2054, 174)
Train Accuracy of SVM  0.9741966893865628
Test Accuracy of SVM   0.9747081712062257
[2. 3. 3. ... 2. 1. 2.]
Confusion matrix: [[ 68   0   0]
 [  1 176   9]
 [  0   3 257]]
0.9780902011193051
0.9783042944581112
0.9782326992004412


In [ ]:
from sklearn.datasets import make_classification
print(f"X_test size {X_test.shape} and X_train size:{X_train.shape}")
rank_classifier = DecisionTreeClassifier(criterion='entropy',max_depth=6, max_leaf_nodes=20, random_state=0)
rank_classifier.fit(X_train,y_train)
Predictions_train=rank_classifier.predict(X_train)
Predictions_test = rank_classifier.predict(X_test)
AccuracyTrain_DT=accuracy_score(y_train,Predictions_train)
AcuuracyTest_DT=accuracy_score(y_test,Predictions_test)
print(f"Accuracy Score of DT for Training Data : {AccuracyTrain_DT} \n Accuracy score of DT for Testing Data :{AcuuracyTest_DT}")
Test = rank_classifier.predict(X_test)
cm = confusion_matrix(y_test, Test)
print ("Confusion matrix:",cm)
y_pred = rank_classifier.predict(X_test)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

X_test size (514, 174) and X_train size:(2054, 174)
Accuracy Score of DT for Training Data : 0.8938656280428432 
 Accuracy score of DT for Testing Data :0.8696498054474708
Confusion matrix: [[ 67   0   1]
 [  3 127  56]
 [  3   4 253]]
0.8797785792758962
0.9011343000970363
0.8803889132162377


In [ ]:
from sklearn.neural_network import MLPClassifier
clf2 = MLPClassifier(alpha=5,hidden_layer_sizes=(300, 6), random_state=1,solver='lbfgs')
sgd = MLPClassifier(alpha=5,hidden_layer_sizes=(300, 6), random_state=1, solver ='sgd',max_iter=500 )
clf2.fit(X_train,y_train)
sgd.fit(X_train,y_train)
pred = clf2.predict(X_test)
predt = clf2.predict(X_train)
TeAccuracy = accuracy_score(y_true = y_test, y_pred = pred)
TrAccuracy = accuracy_score(y_true = y_train, y_pred = predt)
y_pred = clf2.predict(X_test)
Test = clf2.predict(X_test)
cm = confusion_matrix(y_test, Test)
print ("Confusion matrix:",cm)
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))
print("Training Accuracy in Neural Network: {}".format(TrAccuracy))
print("Testing Accuracy in Neural Network: {}".format(TeAccuracy))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


Confusion matrix: [[ 64   4   0]
 [  1 173  12]
 [  0   6 254]]
0.9552849531373231
0.9616192646391094
0.9494023581310108
Training Accuracy in Neural Network: 0.9313534566699123
Testing Accuracy in Neural Network: 0.9552529182879378


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
